// vue-project/vite-ts-vue3/src/App.vue
<!--
 * @Author: TerryMin
 * @Date: 2023-11-14 14:02:39
 * @LastEditors: TerryMin
 * @LastEditTime: 2023-11-14 14:20:53
 * @Description: file not
-->
<script setup lang="ts">
import Home from "./views/home.vue";
</script>

<template>
  <Home />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// react-project/my-app/src/App.js
/*
 * @Author: TerryMin
 * @Date: 2024-09-19 16:52:15
 * @LastEditors: TerryMin
 * @LastEditTime: 2024-09-19 17:03:41
 * @Description: file not
 */
import logo from "./logo.svg";
import "./App.css";
import Profile from "./components/Profile";

function App() {
  return (
    <div className="App">
      <Profile />
    </div>
  );
}

export default App;
