// react-project/my-app/src/App.js
/*
 * @Author: TerryMin
 * @Date: 2024-09-19 16:52:15
 * @LastEditors: TerryMin
 * @LastEditTime: 2024-09-19 17:03:41
 * @Description: file not
 */
import logo from "./logo.svg";
import "./App.css";
import Profile from "./components/Profile";

function App() {
  return (
    <div className="App">
      <Profile />
    </div>
  );
}

export default App;

// vue-project/vite-vue2-project/src/App.vue
<!--
 * @Author: TerryMin
 * @Date: 2022-09-15 09:28:35
 * @LastEditors: TerryMin
 * @LastEditTime: 2022-09-15 14:42:05
 * @Description: file not
-->
<script setup></script>

<template>
  <div id="app">
    <div class="wrapper">
      <nav>
        <router-link to="/">Home</router-link> |
        <router-link to="/about">About</router-link>
      </nav>
    </div>

    <router-view />
  </div>
</template>

<style scoped></style>
