// multi-project/micro-app/micro-app-project/child-app/child-app-react/src/App.js
/*
 * @Author: TerryMin
 * @Date: 2025-04-13 14:49:51
 * @LastEditors: TerryMin
 * @LastEditTime: 2025-04-13 15:36:05
 * @Description: file not
 */
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          child-app-react子应用
        </p>
      </header>
    </div>
  );
}

export default App;

// vue-project/vite-vue2-project/src/App.vue
<!--
 * @Author: TerryMin
 * @Date: 2022-09-15 09:28:35
 * @LastEditors: TerryMin
 * @LastEditTime: 2022-09-15 14:42:05
 * @Description: file not
-->
<script setup></script>

<template>
  <div id="app">
    <div class="wrapper">
      <nav>
        <router-link to="/">Home</router-link> |
        <router-link to="/about">About</router-link>
      </nav>
    </div>

    <router-view />
  </div>
</template>

<style scoped></style>
