// multi-project/micro-app/micro-app-project/child-app/child-app-vue/src/App.vue
<!--
 * @Author: TerryMin
 * @Date: 2025-04-13 15:06:39
 * @LastEditors: TerryMin
 * @LastEditTime: 2025-04-13 15:36:44
 * @Description: file not
-->
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import TheWelcome from './components/TheWelcome.vue'
</script>

<template>
  <header>
    child-app-vue子应用
  </header>

  <main>
    <TheWelcome />
  </main>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>

// multi-project/micro-app/micro-app-project/child-app/child-app-react/src/App.js
/*
 * @Author: TerryMin
 * @Date: 2025-04-13 14:49:51
 * @LastEditors: TerryMin
 * @LastEditTime: 2025-04-13 15:36:05
 * @Description: file not
 */
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          child-app-react子应用
        </p>
      </header>
    </div>
  );
}

export default App;
